Repository UMC-CARDIFY/Client, pull requests merged in 2024-08, with the labels that each got.

#47 [Feat] 로그인 페이지 프로토 구현 완료
  src/assets/images.png
  src/components/MenuBar.jsx
  src/pages/NoteEditor/components/Cards/BlankCard.jsx
  src/pages/NoteEditor/components/Cards/ImageCard.jsx
  src/pages/NoteEditor/components/Cards/MultiCard.jsx
  src/pages/NoteEditor/components/Cards/PreviewModal.jsx
  src/pages/NoteEditor/components/Cards/WordCard.jsx
  src/pages/NoteEditor/components/Editor/CombinedEditor.jsx
  src/pages/NoteEditor/components/Editor/Content.jsx
  src/pages/NoteEditor/components/Editor/Markdown/inputRules.jsx
  src/pages/NoteEditor/components/Editor/Markdown/schema.jsx
  src/pages/NoteEditor/components/Editor/MoreOptions.jsx
  src/pages/NoteEditor/components/Editor/Title.jsx
  src/pages/NoteEditor/components/Editor/ToolBar.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/ColorPalette.jsx
  src/pages/NoteEditor/components/Editor/index.jsx
  src/pages/NoteEditor/components/Header.jsx
  src/pages/NoteEditor/components/KebabMenu/ExportMenu.jsx
  src/pages/NoteEditor/components/KebabMenu/KebabMenu.jsx
  src/pages/NoteEditor/components/MenuBar.jsx
  src/pages/NoteEditor/index.jsx
  src/pages/SignIn/index.jsx
  src/routes/index.jsx
Labels: ✨ Feature

#49 [Feat] 회원가입 페이지 프로토 구현완료
  src/pages/SignUp/index.jsx
  src/pages/SignUp/useFormValidation.jsx
  src/pages/SignUp/validation.jsx
Labels: ✨ Feature

#58 [Feat] 로그인 페이지 api 연동 완료
  src/api/signin/signin.js
Labels: ✨ Feature

#61 [Feat] 회원가입 페이지 모달 추가
  src/components/Modal/PrivacyModal.jsx
  src/components/Modal/TermsModal.jsx
  src/pages/MyPage/index.jsx
  src/pages/SignUp/index.jsx
Labels: ✨ Feature

#62 [Feat] 대시보드 페이지 프로토 구현
  index.html
  public/favicon.svg
  public/vite.svg
  src/assets/.gitkeep
  src/assets/archive.svg
  src/assets/dashbord.svg
  src/assets/flashcard.svg
  src/assets/library.svg
  src/assets/logo.svg
  src/components/MenuBar.jsx
  src/components/TopBar.jsx
  src/pages/Dashboard/components/RecentNote/RecentNoteItem.jsx
  src/pages/Dashboard/components/RecentNote/RecentNotes.jsx
  src/pages/Dashboard/components/StudySuggestion/StudyCalendar.jsx
  src/pages/Dashboard/components/StudySuggestion/StudySuggestions.jsx
  src/pages/Dashboard/components/WeeklyStudy/WeeklyStudyResults.jsx
  src/pages/Dashboard/index.jsx
Labels: ✨ Feature

#68 [Feat] 노트에디터 구현 진행 중
  package-lock.json
  package.json
  src/api/noteeditor/saveNote.js
  src/pages/NoteEditor/components/Cards/MultiCard.jsx
  src/pages/NoteEditor/components/Cards/PreviewModal.jsx
  src/pages/NoteEditor/components/Editor/CombinedEditor.jsx
  src/pages/NoteEditor/components/Editor/Markdown/inputRules.jsx
  src/pages/NoteEditor/components/Editor/Markdown/schema.jsx
  src/pages/NoteEditor/components/Editor/ReactNodeView.js
  src/pages/NoteEditor/components/Editor/ToolBar.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/ColorPalette.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/ToolBar.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/BlankCardButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/BoldButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ColorPalette/HighlightColorPalette.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ColorPalette/TextColorPalette.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/HeadingButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/HighlightColorButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ImageCardButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/MoreOptions/MoreOptions.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/MoreOptionsButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/MultiCardButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/TextColorButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/WordCardButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/style/ToolbarStyles.jsx
  src/pages/NoteEditor/components/Editor/index.jsx
  src/pages/NoteEditor/components/Editor/schema.js
  src/pages/NoteEditor/components/Header.jsx
  src/pages/NoteEditor/components/MenuBar.jsx
  src/pages/NoteEditor/index.jsx
Labels: ✨ Feature

#74 [Feat] 노트에디터 구현 중
  src/api/config.js
  src/api/index.js
  src/api/signin/KaKaoLogin.js
  src/components/SignIn/KakaoLoginButton.jsx
  src/pages/NoteEditor/components/Editor/CombinedEditor.jsx
  src/pages/NoteEditor/components/Editor/Markdown/inputRules.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/ToolBar.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ColorPalette/HighlightColorPalette.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ColorPalette/TextColorPalette.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/HighlightColorButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/TextColorButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/style/ToolbarStyles.jsx
  src/pages/NoteEditor/components/Editor/index.jsx
  src/pages/NoteEditor/components/Editor/setup/schema.jsx
  src/pages/NoteEditor/components/Editor/setup/wordcardView.js
  src/pages/NoteEditor/components/Header.jsx
  src/pages/NoteEditor/index.jsx
  src/pages/SignIn/KaKaoCallback.jsx
  src/pages/SignIn/index.jsx
  src/pages/index.js
  src/routes/index.jsx
  vite.config.js
Labels: ✨ Feature

#78 [Feat] 카카오 소셜 로그인 구현 완료
  src/api/config.js
  src/api/signin/KaKaoLogin.js
  src/components/SignIn/KakaoLoginButton.jsx
  src/pages/SignIn/KaKaoCallback.jsx
Labels: ✨ Feature

#84 [Feat] 노트에디터 노트조회 api 연동
  src/api/NoteContext.jsx
  src/api/index.js
  src/api/noteeditor/getNote.js
  src/main.jsx
  src/pages/NoteEditor/components/Editor/CombinedEditor.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/ToolBar.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ColorPalette/HighlightColorPalette.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ColorPalette/TextColorPalette.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/HeadingButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/HighlightColorButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/TextColorButton.jsx
  src/pages/NoteEditor/components/Editor/index.jsx
  src/pages/NoteEditor/components/Editor/setup/blankcardView.js
  src/pages/NoteEditor/components/Editor/setup/multicardView.js
  src/pages/NoteEditor/components/Editor/setup/schema.jsx
  src/pages/NoteEditor/components/Editor/setup/wordcardView.js
  src/pages/NoteEditor/components/Header/Header.jsx
  src/pages/NoteEditor/components/Header/KebabMenu/DeleteMenu.jsx
  src/pages/NoteEditor/components/Header/KebabMenu/KebabMenu.jsx
  src/pages/NoteEditor/components/Header/KebabMenu/ShareMenu.jsx
  src/pages/NoteEditor/components/MenuBar.jsx
  src/pages/NoteEditor/index.jsx
Labels: ✨ Feature, 📬 API

#86 [Feat] 플래시카드 UI 구현 중
  src/pages/Flashcard/components/CardIcon.jsx
  src/pages/Flashcard/components/DeleteModal.jsx
  src/pages/Flashcard/components/FlashcardItem.jsx
  src/pages/Flashcard/index.jsx
  src/pages/index.js
  src/routes/index.jsx
Labels: ✨ Feature

#89 [chore] 설정 파일 .env로 API URL과 클라이언트 ID 관리
  .gitignore
  src/api/config.js
  src/api/index.js
Labels: 🌏 Deploy

#90 [chore] proxy target 배포 url로 수정
  vite.config.js
Labels: 🌏 Deploy

#91 [chore] 배포 테스트용 코드 수정
  src/pages/SignIn/index.jsx
Labels: 🌏 Deploy

#93 [chore] 자동 배포 테스트용
  src/pages/SignIn/index.jsx
Labels: 🌏 Deploy

#98 [Feat] 노트 클릭 시 노트페이지로 전환되도록 기능 구현
  src/pages/Archive/components/ItemList.jsx
Labels: ✨ Feature

#99 [Feat] 아카이브 프로토 구현
  .env
  src/api/archive/getNoteToFolder.js
  src/assets/closeIcon.svg
  src/assets/deleteIcon.svg
  src/pages/Archive/components/AddButton.jsx
  src/pages/Archive/components/DeleteConfirmModal.jsx
  src/pages/Archive/components/FilteringDropdown.jsx
  src/pages/Archive/components/FolderModal.jsx
  src/pages/Archive/components/FrameRefactor.jsx
  src/pages/Archive/components/ItemList.jsx
  src/pages/Archive/components/MoreDiv.jsx
  src/pages/Archive/components/Pagination.jsx
  src/pages/Archive/components/SortDropdown.jsx
Labels: ✨ Feature

#103 [Feat] 아카이브 필터링 및 정렬 api 연결
  src/api/archive/getFilteringNote.js
  src/api/archive/getFolderFilterSort.js
  src/api/archive/getFolderSort.js
  src/api/archive/getNoteFilterSort.js
  src/api/archive/getNoteSort.js
  src/api/archive/getNoteToFolder.js
  src/api/archive/getNotes.js
  src/api/archive/index.js
  src/assets/checkIconsvg.svg
  src/assets/dropdownArrow.svg
  src/assets/searchIcon.svg
  src/assets/viewAllIcon.svg
  src/pages/Archive/components/FilteringDropdown.jsx
  src/pages/Archive/components/FrameRefactor.jsx
  src/pages/Archive/components/SortDropdown.jsx
  src/pages/Library/components/RecommendationSection.jsx
  src/pages/Library/index.jsx
Labels: ✨ Feature, 📬 API

#109 [Feat] 노트에디터 api 연동 중
  src/api/NoteContext.jsx
  src/api/common/selectFolderModal/fetchFolders.js
  src/api/editor/card/imagecard.js
  src/api/noteeditor/addNote.js
  src/api/noteeditor/deleteNote.js
  src/api/noteeditor/getNote.js
  src/api/noteeditor/getNoteToFolder.js
  src/api/noteeditor/saveNote.js
  src/api/noteeditor/searchNote.js
  src/assets/deleteicon.svg
  src/components/MenuBar.jsx
  src/components/Modal/SelectFolderModal.jsx
  src/components/Modal/style/DeleteModalStyles.jsx
  src/pages/Archive/components/DeleteConfirmModal.jsx
  src/pages/NoteEditor/components/Cards/ImageCard.jsx
  src/pages/NoteEditor/components/Editor/CombinedEditor.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/ColorPalette/HighlightColorPalette.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/style/ToolbarStyles.jsx
  src/pages/NoteEditor/components/Editor/setup/imagecardView.jsx
  src/pages/NoteEditor/components/Editor/setup/multicardView.js
  src/pages/NoteEditor/components/Editor/setup/schema.jsx
  src/pages/NoteEditor/components/Editor/setup/wordcardView.js
  src/pages/NoteEditor/components/Header/Header.jsx
  src/pages/NoteEditor/components/Header/KebabMenu/DeleteMenu.jsx
  src/pages/NoteEditor/components/Header/KebabMenu/ExportMenu.jsx
  src/pages/NoteEditor/components/Header/KebabMenu/KebabMenu.jsx
  src/pages/NoteEditor/components/Header/StarButton.jsx
  src/pages/NoteEditor/components/MenuBar.jsx
  src/pages/NoteEditor/index.jsx
Labels: ✨ Feature, 📬 API

#115 [Style] 폰트 스타일 적용
  src/main.jsx
  src/styles/global.css
Labels: 🎨 Html&css

#117 [Feat] 자료실 프로토 구현
  src/assets/addIcon.svg
  src/assets/closeIcon.svg
  src/pages/Archive/components/AddButton.jsx
  src/pages/Archive/components/FrameRefactor.jsx
  src/pages/Library/components/AllCategory.jsx
  src/pages/Library/components/NoteItem.jsx
  src/pages/Library/components/NoteList.jsx
  src/pages/Library/index.jsx
Labels: ✨ Feature, 🎨 Html&css

#118 [feat] 폴더 선택 모달 구현 완료
  src/api/common/selectFolderModal/writeNote.js
  src/components/Modal/SelectFolderModal.jsx
Labels: ✨ Feature

#120 [Feat] 대시보드 api 연결 중
  src/pages/Dashboard/components/RecentNote/RecentNoteItem.jsx
  src/pages/Dashboard/components/RecentNote/RecentNotes.jsx
Labels: ✨ Feature

#122 [Feat] 마이페이지 유저조회 api 추가
  src/api/mypage/getMypage.js
  src/pages/MyPage/components/ProfileSection.jsx
  src/pages/MyPage/index.jsx
  src/pages/MyPage/styles/MyPageStyles.jsx
Labels: 📬 API

#126 [Feat] 노트에디터 툴바 기능 및 스타일 수정
  src/api/noteeditor/postNoteSearch.js
  src/assets/arrow.svg
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/TextColorButton.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/style/ToolbarStyles.jsx
  src/pages/NoteEditor/components/Header/SearchInput.jsx
Labels: ✨ Feature, 🎨 Html&css

#127 [Feat] 노트 자료실 공유기능 구현
  src/api/noteeditor/shareLib.js
  src/assets/shareLibrary.svg
  src/pages/NoteEditor/components/Header/Header.jsx
  src/pages/NoteEditor/components/Header/KebabMenu/ShareMenu.jsx
Labels: ✨ Feature, 📬 API

#128 [Feat] 자료실 노트 미리보기 렌더링 추가
  src/pages/Library/components/NoteModal.jsx
  src/pages/Library/components/NotePreview.jsx
Labels: ✨ Feature

#130 [Feat] 단어/빈칸/멀티카드 미리보기 구현
  src/assets/noteEditor/bulletIcon.svg
  src/assets/noteEditor/cardPreview.svg
  src/assets/noteEditor/cardPreviewClose.svg
  src/assets/noteEditor/rightArrow.svg
  src/pages/NoteEditor/components/Cards/PreviewModal/blankcardPreview.jsx
  src/pages/NoteEditor/components/Cards/PreviewModal/multicardPreview.jsx
  src/pages/NoteEditor/components/Cards/PreviewModal/style/CardPreviewModalStyles.jsx
  src/pages/NoteEditor/components/Cards/PreviewModal/wordcardPreview.jsx
  src/pages/NoteEditor/components/Editor/ReactNodeView.js
Labels: ✨ Feature

#131 [Feat] 자료실 공유취소 기능구현
  src/api/noteeditor/cancelShare.js
  src/pages/NoteEditor/components/Header/KebabMenu/ShareMenu.jsx
Labels: ✨ Feature, 📬 API

#133 [Feat] 마이페이지 출석체크 구현완료
  src/api/mypage/userCheck.js
  src/pages/MyPage/components/AttendanceButton.jsx
  src/pages/MyPage/index.jsx
Labels: ✨ Feature, 📬 API

#144 [feat] 로그인 엔터 기능 추가
  src/pages/SignIn/index.jsx
Labels: ✨ Feature

#146 [fix] lavender 색 안 넘어오는 에러 수정
  src/components/Modal/SelectFolderModal.jsx
  src/pages/Dashboard/components/RecentNote/RecentNoteItem.jsx
  src/pages/NoteEditor/components/MenuBar.jsx
Labels: 🐞 BugFix

#148 [Fix] 아카이브 기능오류 수정
  src/assets/back.svg
  src/pages/Archive/components/AddButton.jsx
  src/pages/Archive/components/DownloadNote.jsx
  src/pages/Archive/components/FrameRefactor.jsx
  src/pages/Archive/components/ItemList.jsx
  src/pages/Archive/components/SortDropdown.jsx
Labels: ✨ Feature, 🐞 BugFix

#150 [Fix] 아카이브 필터링 오류 수정
  src/pages/Archive/components/Circle.jsx
  src/pages/Archive/components/SortDropdown.jsx
Labels: 🐞 BugFix

#152 [Fix] 필터링 오류 수정
  src/pages/Archive/components/CircleCheck.jsx
  src/pages/Archive/components/FilteringDropdown.jsx
Labels: 🐞 BugFix

#159 feat: 전역 스타일 폰트 적용
  src/styles/GlobalStyle.jsx
Labels: ✨ Feature

#162 [style] 플래시카드 스크롤 메뉴바 안 늘어나게 수정
  src/pages/Flashcard/index.jsx
Labels: 🎨 Html&css

#164 [style] 아카이브 ux ui 수정
  src/pages/Archive/components/ItemList.jsx
Labels: 🎨 Html&css

#165 [Feat] 노트에디터 이미지 카드 api 연결
  src/api/editor/card/imagecard.js
  src/api/noteeditor/imageCard/getNote.js
  src/pages/NoteEditor/components/Cards/ImageCard.jsx
  src/pages/NoteEditor/index.jsx
Labels: ✨ Feature, 📬 API

#170 [Feat] 대시보드 api 연결 중
  package-lock.json
  package.json
  src/api/dashboard/studySuggestions.js
  src/api/dashboard/weeklyStudyResults.js
  src/assets/dashboard/cardIcon.svg
  src/pages/Dashboard/components/StudySuggestion/StudyCalendar.jsx
  src/pages/Dashboard/components/StudySuggestion/StudyCard.jsx
  src/pages/Dashboard/components/StudySuggestion/StudySuggestions.jsx
  src/pages/Dashboard/components/WeeklyStudy/WeeklyStudyResults.jsx
Labels: ✨ Feature, 📬 API

#172 [fix] 학습제안 학습하기로 안 뜨고 음수로 뜨는 에러 수정
  src/pages/Dashboard/components/StudySuggestion/StudyCard.jsx
Labels: 🐞 BugFix

#174 [style] 학습제안 캘린더 호버 클릭 스타일 수정
  src/pages/Dashboard/components/StudySuggestion/StudyCalendar.jsx
Labels: 🎨 Html&css

#179 [feat] 텍스트 블록 추가 툴바에 기본으로 뜨게 수정
  src/pages/NoteEditor/components/Editor/Toolbar/ToolBar.jsx
  src/pages/NoteEditor/components/Editor/Toolbar/components/ToolbarItem/MoreOptions/MoreOptions.jsx
Labels: ✨ Feature
