Repository UMC-CARDIFY/Client, pull requests merged in 2025-01, with the labels that each got.

#4 [Init/#3] 프로젝트 절대 경로 설정 및 관련 설정 추가
  package.json
  pnpm-lock.yaml
  src/apis/.gitkeep
  src/assets/images/.gitkeep
  src/assets/svgs/.gitkeep
  src/components/common/Header.tsx
  src/hooks/.gitkeep
  src/main.tsx
  src/pages/archive/components/.gitkeep
  src/pages/archive/hooks/.gitkeep
  src/pages/archive/index.tsx
  src/pages/archive/types/.gitkeep
  src/pages/index.ts
  src/routes/index.tsx
  src/types/.gitkeep
  src/utils/constants/.gitkeep
  tsconfig.app.json
  vite.config.ts
Labels: ⚙ Setting

#6 [Feat/#1] 아카이브 페이지 컴포넌트 및 헤더 UI 구현
  src/assets/images/index.ts
  src/assets/images/newFolder.webp
  src/assets/svgs/.gitkeep
  src/assets/svgs/ic_archive_innerfolder_28.svg
  src/assets/svgs/ic_archive_kebab_24.svg
  src/assets/svgs/ic_archive_newfolder_24.svg
  src/assets/svgs/ic_archive_plus_12.svg
  src/assets/svgs/ic_common_halfarrowlight_16.svg
  src/assets/svgs/ic_navigation_mypage_28.svg
  src/assets/svgs/ic_navigation_search_20.svg
  src/assets/svgs/index.ts
  src/assets/svgs/logo.svg
  src/components/common/Header.tsx
  src/components/common/header/Header.stories.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/nav.ts
  src/layouts/mainLayout.tsx
  src/pages/archive/components/.gitkeep
  src/pages/archive/components/breadcrumbs/Breadcrumbs.stories.tsx
  src/pages/archive/components/breadcrumbs/Breadcrumbs.tsx
  src/pages/archive/components/insideFolder/InsideFolder.stories.tsx
  src/pages/archive/components/insideFolder/InsideFolder.tsx
  src/pages/archive/components/newFolder/NewFolder.stories.tsx
  src/pages/archive/components/newFolder/NewFolder.tsx
  src/pages/flashcard/index.tsx
  src/pages/index.ts
  src/pages/library/index.tsx
  src/pages/mypage/index.tsx
  src/routes/index.tsx
  src/routes/paths.ts
  tailwind.config.js
Labels: 🎨 Html&css, ✨ Feature

#8 [Release/#7] Stroybook 배포
  .github/workflows/chromatic.yml
  .gitignore
  package.json
  pnpm-lock.yaml
Labels: 🌏 Deploy

#9 [Feat/#5] 노트 리스트 및 노트 추가 버튼 구현
  src/assets/svgs/ic_archive_innerfolder.svg
  src/assets/svgs/ic_archive_kebab.svg
  src/assets/svgs/ic_archive_newfolder.svg
  src/assets/svgs/ic_archive_note.svg
  src/assets/svgs/ic_archive_plus.svg
  src/assets/svgs/ic_archive_star.svg
  src/assets/svgs/ic_checkbox.svg
  src/assets/svgs/ic_common_flashcard.svg
  src/assets/svgs/ic_common_halfarrowlight.svg
  src/assets/svgs/ic_navigation_mypage.svg
  src/assets/svgs/ic_navigation_search.svg
  src/assets/svgs/index.ts
  src/pages/archive/AddNoteButton/AddNoteButton.tsx
  src/pages/archive/components/NoteItem/NoteItem.tsx
  src/pages/archive/components/NoteList/NoteList.stories.tsx
  src/pages/archive/components/NoteList/NoteList.tsx
Labels: 🎨 Html&css, ✨ Feature

#10 [Feat/#2] 아카이브 페이지 모달 UI 구현
  src/assets/svgs/ic_archive_filledstar.svg
  src/assets/svgs/ic_archive_folder.svg
  src/assets/svgs/ic_color_circle.svg
  src/assets/svgs/ic_color_circle_check.svg
  src/assets/svgs/ic_common_alert.svg
  src/assets/svgs/ic_common_x.svg
  src/assets/svgs/ic_search-thin.svg
  src/assets/svgs/index.ts
  src/components/common/Modal.tsx
  src/pages/archive/components/ArchiveFolderIcon.tsx
  src/pages/archive/components/modal/AddFolderModal/AddFolderModal.stories.tsx
  src/pages/archive/components/modal/AddFolderModal/AddFolderModal.tsx
  src/pages/archive/components/modal/AddSubFolderModal/AddSubFolderModal.stories.tsx
  src/pages/archive/components/modal/AddSubFolderModal/AddSubFolderModal.tsx
  src/pages/archive/components/modal/DeleteFolderModal/DeleteFolderModal.stories.tsx
  src/pages/archive/components/modal/DeleteFolderModal/DeleteFolderModal.tsx
  src/pages/archive/components/modal/DeleteNoteModal/DeleteNoteModal.stories.tsx
  src/pages/archive/components/modal/DeleteNoteModal/DeleteNoteModal.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.stories.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.tsx
  src/pages/archive/components/modal/EditSubFolderModal/EditSubFolderModal.stories.tsx
  src/pages/archive/components/modal/EditSubFolderModal/EditSubFolderModal.tsx
  src/pages/archive/components/modal/LimitAddFolderModal/LimitAddFolderModal.stories.tsx
  src/pages/archive/components/modal/LimitAddFolderModal/LimitAddFolderModal.tsx
  src/pages/archive/components/modal/LimitAddNoteModal/LimitAddNoteModal.stories.tsx
  src/pages/archive/components/modal/LimitAddNoteModal/LimitAddNoteModal.tsx
  src/pages/archive/components/modal/MoveFolderModal/MoveFolderModal.stories.tsx
  src/pages/archive/components/modal/MoveFolderModal/MoveFolderModal.tsx
  src/pages/archive/hooks/useColorUtils.ts
  src/styles/colorMap.ts
  tailwind.config.js
Labels: 🎨 Html&css, ✨ Feature

#13 [Feat/#11] 아카이브 내 폴더 내의 노트 화면 구현
  src/assets/svgs/ic_archive_newfolder.svg
  src/assets/svgs/ic_archive_note.svg
  src/assets/svgs/ic_common_slash.svg
  src/assets/svgs/index.ts
  src/mocks/NoteItemData.ts
  src/pages/archive/AddNoteButton/AddNoteButton.tsx
  src/pages/archive/components/NoteItem/NoteItem.tsx
  src/pages/archive/components/NoteList/NoteList.stories.tsx
  src/pages/archive/components/NoteList/NoteList.tsx
  src/pages/archive/components/breadcrumbs/Breadcrumbs.stories.tsx
  src/pages/archive/components/breadcrumbs/Breadcrumbs.tsx
  src/pages/archive/components/emptyState/EmptyNoteState.stories.tsx
  src/pages/archive/components/emptyState/EmptyNoteState.tsx
  src/pages/archive/components/folderNameHeader/FolderNameHeader.tsx
  src/pages/archive/components/folderNameHeader/folderNameHeader.stories.tsx
  src/pages/archive/components/insideFolder/InsideFolder.stories.tsx
  src/pages/archive/components/insideFolder/InsideFolder.tsx
  src/pages/archive/components/insideFolderList/InsideFolderList.stories.tsx
  src/pages/archive/components/insideFolderList/InsideFolderList.tsx
  src/pages/archive/pages/NotesInsideFolderPage.stories.tsx
  src/pages/archive/pages/NotesInsideFolderPage.tsx
Labels: 🎨 Style, ✨ Feature
