Repository UMC-CARDIFY/Client, pull requests merged in 2025-08, with the labels that each got.

#74 [Feat/#65] 노트 에디터 툴팁 및 제목 구현
  package.json
  pnpm-lock.yaml
  src/assets/svgs/ic_full_flashcard.svg
  src/assets/svgs/index.ts
  src/pages/note-editor/components/tiptap-icons/strike-icon.tsx
  src/pages/note-editor/components/tiptap-node/paragraph-node/paragraph-node.scss
  src/pages/note-editor/components/tiptap-templates/simple/editor-title/editor-title.scss
  src/pages/note-editor/components/tiptap-templates/simple/editor-title/editor-title.tsx
  src/pages/note-editor/components/tiptap-templates/simple/editor-title/index.tsx
  src/pages/note-editor/components/tiptap-templates/simple/simple-editor.scss
  src/pages/note-editor/components/tiptap-templates/simple/simple-editor.tsx
  src/pages/note-editor/components/tiptap-ui-primitive/button/button.scss
  src/pages/note-editor/components/tiptap-ui-primitive/dropdown-menu/dropdown-menu.scss
  src/pages/note-editor/components/tiptap-ui-primitive/tooltip/tooltip.scss
  src/pages/note-editor/components/tiptap-ui-primitive/tooltip/tooltip.tsx
  src/pages/note-editor/components/tiptap-ui/code-block-button/code-block-button.tsx
  src/pages/note-editor/components/tiptap-ui/color-highlight-popover/color-highlight-popover.tsx
  src/pages/note-editor/components/tiptap-ui/color-text-popover/color-text-popover.tsx
  src/pages/note-editor/components/tiptap-ui/heading-dropdown-menu/heading-dropdown-menu.scss
  src/pages/note-editor/components/tiptap-ui/heading-dropdown-menu/heading-dropdown-menu.tsx
  src/pages/note-editor/components/tiptap-ui/list-button/list-button.tsx
  src/pages/note-editor/components/tiptap-ui/mark-button/mark-button.tsx
  src/pages/note-editor/components/tiptap-ui/math-block-button/math-block-button.tsx
  src/pages/note-editor/components/tiptap-ui/search-note/search-note.scss
  src/pages/note-editor/components/tiptap-ui/search-note/search-note.tsx
  src/pages/note-editor/styles/_variables.scss
Labels: ✨ Feature

#80 [Fix/#79] 타이포 시스템 수정으로 인한 문제
  src/components/common/Modal.tsx
  src/components/common/dropdown/Kebab.tsx
  src/components/common/dropdown/NoteFilter.tsx
  src/components/common/dropdown/Sort.tsx
  src/components/common/dropdown/colorPicker/ColorPicker.tsx
  src/components/common/header/Header.tsx
  src/components/common/pagination/Pagination.tsx
  src/pages/archive/components/EmptyState/EmptyState.tsx
  src/pages/archive/components/MainFolderItem/MainFolderItem.tsx
  src/pages/archive/components/NoteItem/NoteItem.tsx
  src/pages/archive/components/NoteList/NoteList.tsx
  src/pages/archive/components/breadcrumbs/Breadcrumbs.tsx
  src/pages/archive/components/folderNameHeader/FolderNameHeader.tsx
  src/pages/archive/components/insideFolder/InsideFolder.tsx
  src/pages/archive/components/insideFolderList/InsideFolderList.tsx
  src/pages/archive/components/modal/AddFolderModal/AddFolderModal.tsx
  src/pages/archive/components/modal/AddSubFolderModal/AddSubFolderModal.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.tsx
  src/pages/archive/components/modal/EditSubFolderModal/EditSubFolderModal.tsx
  src/pages/archive/components/modal/MoveFolderModal/MoveFolderModal.tsx
  src/pages/archive/pages/NotesInsideFolderPage.tsx
  src/pages/archive/pages/index.tsx
  src/pages/home/components/EmptyState/EmptyState.tsx
  src/pages/home/components/RecentMarkedNote/RecentMarkedNoteItem.tsx
  src/pages/home/components/ScheduledLearning/ScheduledLearningItem.tsx
  src/pages/home/index.tsx
  src/pages/subscribe/components/subscribe-card/subscribe-card.stories.tsx
Labels: 👾 Fix

#83 [Feature/#82] 빌드 오류 검사 추가
  .github/workflows/ci.yml
Labels: ⚙ Setting
