Repository UMC-CARDIFY/Client, pull requests merged in 2025-03, with the labels that each got.

#27 [Feat/#24, #26] 로그인 뷰 퍼블리싱 및 소셜 로그인 연동
  .gitignore
  package.json
  pnpm-lock.yaml
  src/assets/svgs/btn_login_google.svg
  src/assets/svgs/btn_login_kakao.svg
  src/assets/svgs/ic_login_google.svg
  src/assets/svgs/ic_login_gradient.svg
  src/assets/svgs/ic_login_kakao.svg
  src/assets/svgs/index.ts
  src/assets/svgs/symbol_logo.svg
  src/pages/archive/components/NoteItem/NoteItem.tsx
  src/pages/index.ts
  src/pages/login/components/GoogleButton/GoogleButton.tsx
  src/pages/login/components/kakaoButton/KakaoButton.tsx
  src/pages/login/index.tsx
  src/pages/login/pages/Login.stories.tsx
  src/pages/login/pages/Login.tsx
  src/routes/index.tsx
  src/routes/paths.ts
Labels: ✨ Feature

#30 [Feat/#25] 아카이브 화면 퍼블리싱
  src/assets/svgs/ic_archive_plus.svg
  src/components/common/Modal.tsx
  src/mocks/FolderItemData.ts
  src/mocks/InsideFolderItemData.ts
  src/mocks/NoteItemData.ts
  src/pages/archive/AddNoteButton/AddNoteButton.tsx
  src/pages/archive/components/MainFolderItem/MainFolderItem.tsx
  src/pages/archive/components/MainFolderList/MainFolderList.tsx
  src/pages/archive/components/NoteItem/NoteItem.tsx
  src/pages/archive/components/NoteList/NoteList.tsx
  src/pages/archive/components/folderNameHeader/FolderNameHeader.tsx
  src/pages/archive/components/insideFolder/InsideFolder.tsx
  src/pages/archive/components/modal/AddFolderModal/AddFolderModal.tsx
  src/pages/archive/components/modal/AddSubFolderModal/AddSubFolderModal.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.stories.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.tsx
  src/pages/archive/components/modal/EditSubFolderModal/EditSubFolderModal.tsx
  src/pages/archive/components/modal/MoveFolderModal/MoveFolderModal.stories.tsx
  src/pages/archive/components/modal/MoveFolderModal/MoveFolderModal.tsx
  src/pages/archive/components/newFolder/NewFolderMain.tsx
  src/pages/archive/index.tsx
  src/pages/archive/pages/NotesInsideFolderPage.tsx
  src/pages/archive/pages/index.stories.tsx
  src/pages/archive/pages/index.tsx
  src/pages/index.ts
  src/types/folder.ts
Labels: 🎨 Style, ✨ Feature

#38 [Feat/#34] axios 초기세팅
  package.json
  pnpm-lock.yaml
  src/apis/.gitkeep
  src/apis/config/axiosInstance.ts
Labels: ✨ Feature

#40 [Fix/#39] lint 에러 해결
  src/components/common/dropdown/Kebab.tsx
  src/components/common/dropdown/NoteFilter.tsx
  src/components/common/dropdown/Sort.tsx
  src/components/common/dropdown/colorPicker/ColorPicker.tsx
  src/pages/archive/components/ArchiveFolderIcon.tsx
  src/pages/archive/components/MainFolderItem/ArchiveMainFolderIcon.tsx
  src/pages/archive/components/StarIcon.tsx
  src/pages/archive/components/modal/AddFolderModal/AddFolderModal.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.tsx
  src/pages/archive/components/modal/MoveFolderModal/MoveFolderModal.tsx
Labels: 👾 Fix

#42 [Style/#41] 케밥 스타일 수정
  src/components/common/dropdown/DropdownContainer.tsx
  src/components/common/header/Header.stories.tsx
  src/pages/archive/pages/NotesInsideFolderPage.stories.tsx
  src/pages/home/components/RecentMarkedNote/RecentMarkedNoteItem.stories.tsx
  src/pages/home/components/RecentMarkedNote/RecentMarkedNoteList.stories.tsx
  src/pages/home/components/ScheduledLearning/ScheduledLearningItem.stories.tsx
  src/pages/home/components/ScheduledLearning/ScheduledLearningList.stories.tsx
  src/pages/home/index.stories.tsx
Labels: 🎨 Style, ✨ Feature
