Repository UMC-CARDIFY/Client, pull requests merged in 2025-07, with the labels that each got.

#68 [Refactor/#59] 아카이브 리팩토링 및 에러 해결
  src/assets/svgs/ic_archive_emptystar.svg
  src/pages/archive/components/MainFolderItem/MainFolderItem.tsx
  src/pages/archive/components/modal/AddFolderModal/AddFolderModal.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.tsx
  src/pages/archive/hooks/use-folder.ts
Labels: 🛠️ Refactor, 👾 Fix

#67 [Feature/#66] 공통 버튼 구현
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.tsx
  src/components/typography/Text.tsx
Labels: ✨ Feature

#73 [Chore/#70] editorconfig 및 gitattributes 추가
  .editorconfig
  .gitattributes
Labels: 👾 Fix
