Repository UMC-CARDIFY/Client, pull requests merged in 2025-02, with the labels that each got.

#14 [Feat/#12] 아카이브 메인 화면 폴더 있는 상태 UI 구현
  src/assets/images/index.ts
  src/assets/images/newFolderMain.webp
  src/assets/svgs/ic_archive_emptystar.svg
  src/assets/svgs/ic_archive_filledstar.svg
  src/assets/svgs/index.ts
  src/components/common/Modal.tsx
  src/mocks/FolderItemData.ts
  src/pages/archive/components/MainFolderItem/ArchiveMainFolderIcon.tsx
  src/pages/archive/components/MainFolderItem/MainFolderItem.tsx
  src/pages/archive/components/MainFolderList/MainFolderList.stories.tsx
  src/pages/archive/components/MainFolderList/MainFolderList.tsx
  src/pages/archive/components/StarIcon.tsx
  src/pages/archive/components/modal/AddFolderModal/AddFolderModal.stories.tsx
  src/pages/archive/components/modal/AddFolderModal/AddFolderModal.tsx
  src/pages/archive/components/modal/AddSubFolderModal/AddSubFolderModal.stories.tsx
  src/pages/archive/components/modal/AddSubFolderModal/AddSubFolderModal.tsx
  src/pages/archive/components/modal/DeleteFolderModal/DeleteFolderModal.stories.tsx
  src/pages/archive/components/modal/DeleteNoteModal/DeleteNoteModal.stories.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.stories.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.tsx
  src/pages/archive/components/modal/EditSubFolderModal/EditSubFolderModal.stories.tsx
  src/pages/archive/components/modal/EditSubFolderModal/EditSubFolderModal.tsx
  src/pages/archive/components/modal/LimitAddFolderModal/LimitAddFolderModal.stories.tsx
  src/pages/archive/components/modal/LimitAddNoteModal/LimitAddNoteModal.stories.tsx
  src/pages/archive/components/modal/MoveFolderModal/MoveFolderModal.stories.tsx
  src/pages/archive/components/newFolder/NewFolderMain.tsx
Labels: 🎨 Style, ✨ Feature

#19 [Feat/#18] 홈화면 컴포넌트 구현
  src/App.tsx
  src/assets/svgs/ic_home_flashcard.svg
  src/assets/svgs/index.ts
  src/pages/archive/components/NoteItem/NoteItem.tsx
  src/pages/home/components/RecentMarkedNote/RecentMarkedNoteItem.stories.tsx
  src/pages/home/components/RecentMarkedNote/RecentMarkedNoteItem.tsx
  src/pages/home/components/RecentMarkedNote/RecentMarkedNoteList.stories.tsx
  src/pages/home/components/RecentMarkedNote/RecentMarkedNoteList.tsx
  src/pages/home/components/ScheduledLearning/ScheduledLearningItem.stories.tsx
  src/pages/home/components/ScheduledLearning/ScheduledLearningItem.tsx
  src/pages/home/components/ScheduledLearning/ScheduledLearningList.stories.tsx
  src/pages/home/components/ScheduledLearning/ScheduledLearningList.tsx
  src/pages/home/index.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/styles/colors.ts
  src/types/.gitkeep
  src/types/note.ts
  src/types/scheduledLearning.ts
  tailwind.config.js
Labels: 🎨 Style, ✨ Feature

#23 [Feat/#22] 페이지네이션 구현
  src/assets/svgs/ic_common_halfarrowbold.svg
  src/assets/svgs/ic_common_halfarrowdoublebold.svg
  src/assets/svgs/index.ts
  src/components/common/pagination/Pagination.stories.tsx
  src/components/common/pagination/Pagination.tsx
Labels: ✨ Feature

#21 [Feat/#17] 드롭다운 버튼 구현
  src/assets/svgs/ic_achive_filtering.svg
  src/assets/svgs/ic_archive_sort.svg
  src/assets/svgs/ic_common_x_20.svg
  src/assets/svgs/index.ts
  src/components/common/dropdown/DropdownContainer.tsx
  src/components/common/dropdown/FolderFilter.stories.tsx
  src/components/common/dropdown/FolderFilter.tsx
  src/components/common/dropdown/Kebab.stories.tsx
  src/components/common/dropdown/Kebab.tsx
  src/components/common/dropdown/NoteFilter.stories.tsx
  src/components/common/dropdown/NoteFilter.tsx
  src/components/common/dropdown/Sort.stories.tsx
  src/components/common/dropdown/Sort.tsx
  src/components/common/dropdown/colorPicker/ColorPicker.tsx
  src/pages/archive/pages/NotesInsideFolderPage.tsx
  src/utils/dropdownHandlers.ts
Labels: ✨ Feature

#16 [Feat/#15] 폴더 없을 때 컴포넌트 구현
  src/pages/archive/components/EmptyState/EmptyState.stories.tsx
  src/pages/archive/components/EmptyState/EmptyState.tsx
  src/pages/archive/components/NoteList/NoteList.tsx
  src/pages/archive/components/emptyState/EmptyNoteState.stories.tsx
  src/pages/archive/components/emptyState/EmptyNoteState.tsx
Labels: 🛠️ Refactor, ✨ Feature
