Repository UMC-CARDIFY/Client, pull requests merged in 2025-05, with the labels that each got.

#48 [Feat/#47] 폴더 삭제 및 즐겨찾기 api 구현
  src/apis/common/methods.ts
  src/apis/folder/folder-queries.ts
  src/apis/folder/folder.ts
  src/constants/api.ts
  src/hooks/.gitkeep
  src/hooks/folder/use-folder.ts
  src/mocks/FolderItemData.ts
  src/mocks/InsideFolderItemData.ts
  src/pages/archive/components/MainFolderItem/MainFolderItem.tsx
  src/pages/archive/components/MainFolderList/MainFolderList.tsx
  src/pages/archive/components/folderNameHeader/FolderNameHeader.tsx
  src/pages/archive/components/insideFolder/InsideFolder.stories.tsx
  src/pages/archive/components/insideFolder/InsideFolder.tsx
  src/pages/archive/components/insideFolderList/InsideFolderList.stories.tsx
  src/pages/archive/components/insideFolderList/InsideFolderList.tsx
  src/pages/archive/components/modal/DeleteFolderModal/DeleteFolderModal.tsx
  src/pages/archive/components/modal/MoveFolderModal/MoveFolderModal.stories.tsx
  src/pages/archive/components/modal/MoveFolderModal/MoveFolderModal.tsx
  src/pages/archive/hooks/use-folder-list.ts
  src/pages/archive/pages/NotesInsideFolderPage.stories.tsx
  src/pages/archive/pages/index.stories.tsx
  src/pages/home/index.stories.tsx
  src/types/folder-response.ts
  src/types/folder.ts
  src/utils/folder-mapper.ts
Labels: ✨ Feature

#52 [Fix/#51] 스토리북 UI test 에러 해결
  .storybook/preview.ts
  .storybook/preview.tsx
  src/pages/archive/components/folderNameHeader/FolderNameHeader.tsx
  src/pages/archive/components/folderNameHeader/folderNameHeader.stories.tsx
  src/pages/archive/components/modal/DeleteFolderModal/DeleteFolderModal.stories.tsx
  src/pages/archive/components/modal/DeleteNoteModal/DeleteNoteModal.tsx
Labels: 👾 Fix

#54 [Feat/#53] 노트에디터 페이지 초기세팅
  src/layouts/noteLayout.tsx
  src/pages/note-editor/components/editor/index.tsx
  src/pages/note-editor/components/header/index.tsx
  src/pages/note-editor/components/sidebar/index.tsx
  src/routes/index.tsx
  src/routes/paths.ts
Labels: ✨ Feature

#49 [Feat/#46] 아카이브 api 연결
  .storybook/preview.tsx
  biome.json
  src/apis/folder/folder-queries.ts
  src/apis/folder/folder.ts
  src/components/common/dropdown/Kebab.tsx
  src/constants/api.ts
  src/pages/archive/components/AddNoteButton/AddNoteButton.tsx
  src/pages/archive/components/EmptyState/EmptyState.tsx
  src/pages/archive/components/MainFolderItem/MainFolderItem.tsx
  src/pages/archive/components/modal/AddFolderModal/AddFolderModal.tsx
  src/pages/archive/components/modal/EditFolderModal/EditFolderModal.tsx
  src/pages/archive/components/newFolder/NewFolderMain.tsx
  src/pages/archive/hooks/use-folder.ts
  src/pages/archive/pages/NotesInsideFolderPage.tsx
  src/routes/index.tsx
Labels: 🛠️ Refactor, ✨ Feature

#58 [Feat/#57] 노트에디터 헤더 구현
  src/apis/folder/folder-queries.ts
  src/apis/folder/folder.ts
  src/assets/svgs/ic_archive_emptystar.svg
  src/assets/svgs/ic_note_link.svg
  src/assets/svgs/index.ts
  src/components/common/header/Header.tsx
  src/components/common/header/nav.ts
  src/constants/paths.ts
  src/hooks/folder/use-folder.ts
  src/layouts/noteLayout.tsx
  src/pages/archive/components/MainFolderItem/MainFolderItem.tsx
  src/pages/home/components/EmptyState/EmptyState.tsx
  src/pages/note-editor/components/button/button.tsx
  src/pages/note-editor/components/header/header.tsx
  src/pages/note-editor/components/header/index.tsx
  src/routes/index.tsx
Labels: 🎨 Style, ✨ Feature
